# Generated by Django 3.0 on 2024-01-17 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_Name', models.CharField(max_length=100)),
                ('Brand_Desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Cartmast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Amount', models.CharField(max_length=100)),
                ('Cart_Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(max_length=100)),
                ('Cat_Desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Fname', models.CharField(max_length=100)),
                ('Customer_Lname', models.CharField(max_length=100)),
                ('Customer_City', models.CharField(max_length=100)),
                ('Customer_House', models.CharField(max_length=100)),
                ('Customer_Dist', models.CharField(max_length=100)),
                ('Customer_Pin', models.CharField(max_length=100)),
                ('Customer_Place', models.CharField(max_length=100)),
                ('Customer_Phone', models.CharField(max_length=100)),
                ('Customer_Gender', models.CharField(max_length=100)),
                ('Customer_DOB', models.CharField(max_length=100)),
                ('Customer_Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Login',
            fields=[
                ('Username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('User_Type', models.CharField(max_length=100)),
                ('User_Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Date', models.CharField(max_length=100)),
                ('Order_Amount', models.CharField(max_length=100)),
                ('Bill_No', models.CharField(max_length=100)),
                ('A_Fname', models.CharField(max_length=100)),
                ('A_Lname', models.CharField(max_length=100)),
                ('A_City', models.CharField(max_length=100)),
                ('A_House', models.CharField(max_length=100)),
                ('A_Dist', models.CharField(max_length=100)),
                ('A_Pin', models.CharField(max_length=100)),
                ('A_Place', models.CharField(max_length=100)),
                ('A_Phone', models.CharField(max_length=100)),
                ('Order_Status', models.CharField(max_length=100)),
                ('CART_MASTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_Cartmast')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subcat_Name', models.CharField(max_length=100)),
                ('Subcat_Desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_Fname', models.CharField(max_length=100)),
                ('Staff_Lname', models.CharField(max_length=100)),
                ('Staff_City', models.CharField(max_length=100)),
                ('Staff_House', models.CharField(max_length=100)),
                ('Staff_Dist', models.CharField(max_length=100)),
                ('Staff_Pin', models.CharField(max_length=100)),
                ('Staff_Place', models.CharField(max_length=100)),
                ('Staff_Phone', models.CharField(max_length=100)),
                ('Staff_Gender', models.CharField(max_length=100)),
                ('Staff_Photo', models.ImageField(upload_to='static/staff')),
                ('Staff_DOB', models.CharField(max_length=100)),
                ('Staff_Status', models.CharField(max_length=100)),
                ('Staff_Type', models.CharField(max_length=100)),
                ('USERNAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_Login')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review_Desc', models.CharField(max_length=100)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_Customer')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Date', models.CharField(max_length=100)),
                ('Payment_Status', models.CharField(max_length=100)),
                ('CARD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_Cartmast')),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_Order')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=100)),
                ('Item_Image', models.ImageField(upload_to='static')),
                ('Item_Price', models.CharField(max_length=100)),
                ('Item_Desc', models.CharField(max_length=100)),
                ('Item_Status', models.CharField(max_length=100)),
                ('BRAND', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_Brand')),
                ('CAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_Category')),
                ('SUBCAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_Subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Dassign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dassign_Date', models.CharField(max_length=100)),
                ('Delivery_Date', models.CharField(max_length=100)),
                ('Delivery_Status', models.CharField(max_length=100)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_Customer')),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_Order')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_customer',
            name='USERNAME',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_Login'),
        ),
        migrations.AddField(
            model_name='tbl_cartmast',
            name='CUSTOMER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_Customer'),
        ),
        migrations.CreateModel(
            name='tbl_Cartchild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cart_Quantity', models.CharField(max_length=100)),
                ('CART_MASTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_Cartmast')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_Item')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_No', models.CharField(max_length=100)),
                ('Card_Holdername', models.CharField(max_length=100)),
                ('Expire_Date', models.CharField(max_length=100)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_Customer')),
            ],
        ),
    ]
