# Generated by Django 3.0 on 2024-02-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_prestige_watch_marketplace_app', '0005_auto_20240117_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_item',
            name='Item_Image',
            field=models.ImageField(upload_to='static/item'),
        ),
    ]
