# Generated by Django 3.0 on 2024-02-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_prestige_watch_marketplace_app', '0006_auto_20240214_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_dassign',
            name='CUSTOMER',
        ),
        migrations.AddField(
            model_name='tbl_dassign',
            name='STAFF',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_Staff'),
            preserve_default=False,
        ),
    ]
