# Generated by Django 3.2.22 on 2024-02-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_prestige_watch_marketplace_app', '0008_auto_20240217_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_review',
            name='ITEM',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_item'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_Vassign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vassign_Date', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('ITEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_item')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_staff')),
            ],
        ),
    ]
