# Generated by Django 3.0 on 2024-02-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_prestige_watch_marketplace_app', '0010_auto_20240219_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_item',
            name='second_status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
