# Generated by Django 3.0 on 2024-02-18 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_prestige_watch_marketplace_app', '0012_tbl_item_third_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_item',
            name='CUSTOMER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_prestige_watch_marketplace_app.tbl_Customer'),
            preserve_default=False,
        ),
    ]
